name: Docker CI Pipeline

# කෝඩ් එක main branch එකට push කරපු ගමන් මේක වැඩ කරන්න ඕනේ
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # GitHub එකේ තියෙන Ubuntu සර්වර් එකක් මේකට පාවිච්චි කරන්න
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build the Docker Image
      run: docker build -t my-website-image:latest .
